import { and, desc, eq, like, or, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { visitorLogs } from "../../../db/schema";
import { VISIT_STATUSES, validVisitTimes } from "../../visitor-log";
import { addAudit, ADMIN_ROLES, auditDifference, requireRole, WRITE_ROLES } from "../../security";
import { readListQuery } from "../list-query";
import { cleanText, isIsoDate, parsePositiveId, serverError } from "../validation";

function parsePayload(payload:Record<string,unknown>){
 const values={visitNumber:cleanText(payload.visitNumber,60),visitorName:cleanText(payload.visitorName,150),origin:cleanText(payload.origin,150),purpose:cleanText(payload.purpose,500),staffToMeet:cleanText(payload.staffToMeet,150),visitDate:String(payload.visitDate??""),checkInTime:String(payload.checkInTime??""),checkOutTime:String(payload.checkOutTime??""),status:cleanText(payload.status,40),resultNotes:cleanText(payload.resultNotes,2000)};
 if(!values.visitNumber||!values.visitorName||!values.origin||!values.purpose||!values.staffToMeet)return{error:"Nomor kunjungan, nama tamu, asal, tujuan, dan staf yang ditemui wajib diisi."};
 if(!isIsoDate(values.visitDate)||!validVisitTimes(values.checkInTime,values.checkOutTime))return{error:"Tanggal atau waktu kunjungan tidak valid."};
 if(!VISIT_STATUSES.includes(values.status as typeof VISIT_STATUSES[number]))return{error:"Status kunjungan tidak valid."};
 if(values.status==="Selesai"&&!values.checkOutTime)return{error:"Jam keluar wajib diisi ketika kunjungan selesai."};
 return{values};
}
export async function GET(request:Request){try{const auth=await requireRole(request,WRITE_ROLES);if("response"in auth)return auth.response;const{page,perPage,offset,query,params}=readListQuery(request),status=(params.get("status")??"").trim(),date=(params.get("date")??"").trim(),conditions=[];if(query){const p=`%${query}%`;conditions.push(or(like(visitorLogs.visitNumber,p),like(visitorLogs.visitorName,p),like(visitorLogs.origin,p),like(visitorLogs.purpose,p),like(visitorLogs.staffToMeet,p)))}if(status&&status!=="Semua")conditions.push(eq(visitorLogs.status,status));if(isIsoDate(date))conditions.push(eq(visitorLogs.visitDate,date));const where=conditions.length?and(...conditions):undefined,today=new Date().toISOString().slice(0,10),db=await getDb();const[items,[total],[summary]]=await Promise.all([db.select().from(visitorLogs).where(where).orderBy(desc(visitorLogs.visitDate),desc(visitorLogs.checkInTime)).limit(perPage).offset(offset),db.select({value:sql<number>`count(*)`}).from(visitorLogs).where(where),db.select({total:sql<number>`count(*)`,today:sql<number>`sum(case when ${visitorLogs.visitDate}=${today} then 1 else 0 end)`,inside:sql<number>`sum(case when ${visitorLogs.status}='Di Kantor' then 1 else 0 end)`,completed:sql<number>`sum(case when ${visitorLogs.status}='Selesai' then 1 else 0 end)`}).from(visitorLogs)]);return Response.json({visitors:items,pagination:{page,perPage,total:Number(total?.value??0)},summary:{total:Number(summary?.total??0),today:Number(summary?.today??0),inside:Number(summary?.inside??0),completed:Number(summary?.completed??0)},currentUser:auth.user})}catch(e){return serverError(e)}}
export async function POST(request:Request){try{const auth=await requireRole(request,WRITE_ROLES);if("response"in auth)return auth.response;const parsed=parsePayload(await request.json() as Record<string,unknown>);if("error"in parsed)return Response.json({error:parsed.error},{status:400});const db=await getDb();const[dupe]=await db.select({id:visitorLogs.id}).from(visitorLogs).where(eq(visitorLogs.visitNumber,parsed.values.visitNumber)).limit(1);if(dupe)return Response.json({error:"Nomor kunjungan sudah digunakan."},{status:409});const[item]=await db.insert(visitorLogs).values(parsed.values).returning();await addAudit(auth.user,"Tambah buku tamu","Buku Tamu",`${item.visitNumber} — ${item.visitorName}`,{entityId:item.id});return Response.json({visitor:item},{status:201})}catch(e){return serverError(e)}}
export async function PATCH(request:Request){try{const auth=await requireRole(request,WRITE_ROLES);if("response"in auth)return auth.response;const p=await request.json() as Record<string,unknown>,id=parsePositiveId(p.id);if(!id)return Response.json({error:"ID kunjungan tidak valid."},{status:400});const parsed=parsePayload(p);if("error"in parsed)return Response.json({error:parsed.error},{status:400});const db=await getDb(),[before]=await db.select().from(visitorLogs).where(eq(visitorLogs.id,id)).limit(1);if(!before)return Response.json({error:"Kunjungan tidak ditemukan."},{status:404});const[item]=await db.update(visitorLogs).set({...parsed.values,updatedAt:new Date().toISOString()}).where(eq(visitorLogs.id,id)).returning();await addAudit(auth.user,"Perbarui buku tamu","Buku Tamu",`${item.visitNumber} — ${item.status}`,auditDifference(before,item,id));return Response.json({visitor:item})}catch(e){return serverError(e)}}
export async function DELETE(request:Request){try{const auth=await requireRole(request,ADMIN_ROLES);if("response"in auth)return auth.response;const id=parsePositiveId((await request.json() as{id?:unknown}).id);if(!id)return Response.json({error:"ID kunjungan tidak valid."},{status:400});const[item]=await(await getDb()).delete(visitorLogs).where(eq(visitorLogs.id,id)).returning();if(!item)return Response.json({error:"Kunjungan tidak ditemukan."},{status:404});await addAudit(auth.user,"Hapus buku tamu","Buku Tamu",`${item.visitNumber} — ${item.visitorName}`,{entityId:id});return Response.json({success:true})}catch(e){return serverError(e)}}
