"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Icon from "./Icon";
import { useLanguage } from "./LanguageProvider";
import Pagination from "./Pagination";
import { ToastContainer, useToast } from "./Toast";
import { roleHasCapability } from "../roles";
import { OFFICE_EVENT_PRIORITIES, OFFICE_EVENT_STATUSES, OFFICE_EVENT_TYPES } from "../office-calendar";

type EventItem = { id:number; title:string; eventType:string; eventDate:string; startTime:string; endTime:string; location:string; responsiblePerson:string; priority:string; status:string; description:string; overdue:boolean };
const today=()=>new Date().toISOString().slice(0,10);
const blank={title:"",eventType:"Rapat",eventDate:today(),startTime:"08:00",endTime:"",location:"",responsiblePerson:"",priority:"Normal",status:"Dijadwalkan",description:""};

export default function OfficeCalendar(){
 const {t}=useLanguage(); const {toasts,addToast,dismiss}=useToast();
 const [events,setEvents]=useState<EventItem[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<EventItem|null>(null);
 const [show,setShow]=useState(false),[role,setRole]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [query,setQuery]=useState(""),[status,setStatus]=useState("Semua"),[month,setMonth]=useState(today().slice(0,7)),[page,setPage]=useState(1),[total,setTotal]=useState(0);
 const [summary,setSummary]=useState({total:0,today:0,upcoming:0,overdue:0}); const perPage=12; const canWrite=roleHasCapability(role,"writeOperational");
 const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams({page:String(page),perPage:String(perPage),q:query,status,month});const r=await fetch(`/api/calendar?${p}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setEvents(d.events);setSummary(d.summary);setTotal(d.pagination.total);setRole(d.currentUser.role)}catch(e){addToast(t(e instanceof Error?e.message:"Agenda belum dapat dimuat."),"error")}finally{setLoading(false)}},[addToast,month,page,query,status,t]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer)},[load]);
 function openCreate(){setEditing(null);setForm({...blank,eventDate:today()});setShow(true)}
 function openEdit(e:EventItem){setEditing(e);setForm({title:e.title,eventType:e.eventType,eventDate:e.eventDate,startTime:e.startTime,endTime:e.endTime,location:e.location,responsiblePerson:e.responsiblePerson,priority:e.priority,status:e.status,description:e.description});setShow(true)}
 async function submit(ev:FormEvent){ev.preventDefault();setSaving(true);try{const r=await fetch("/api/calendar",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{id:editing.id,...form}:form)});const d=await r.json();if(!r.ok)throw new Error(d.error);addToast(t(editing?"Agenda berhasil diperbarui.":"Agenda berhasil ditambahkan."),"success");setShow(false);await load()}catch(e){addToast(t(e instanceof Error?e.message:"Agenda belum dapat disimpan."),"error")}finally{setSaving(false)}}
 async function remove(e:EventItem){if(!confirm(`${t("Hapus agenda ini? Tindakan ini tidak dapat dibatalkan.")}\n\n${e.title}`))return;const r=await fetch("/api/calendar",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:e.id})});const d=await r.json();if(!r.ok)return addToast(t(d.error),"error");addToast(t("Agenda berhasil dihapus."),"success");await load()}
 return <div className="page mail-page calendar-page"><div className="page-heading"><div><p className="eyebrow">{t("JADWAL KANTOR")}</p><h1>{t("Kalender & Agenda")}</h1><p>{t("Atur rapat, kegiatan, kunjungan, pelayanan, dan tenggat kantor.")}</p></div>{canWrite&&<button className="primary-button mail-add" onClick={openCreate}><Icon name="plus"/>{t("Tambah Agenda")}</button>}</div>
 <section className="mail-stats calendar-stats"><article><span>{t("Total Agenda")}</span><strong>{summary.total}</strong><small>{month}</small></article><article><span>{t("Hari Ini")}</span><strong>{summary.today}</strong><small>{t("Perlu diperhatikan")}</small></article><article><span>{t("Akan Datang")}</span><strong>{summary.upcoming}</strong><small>{t("Sudah dijadwalkan")}</small></article><article><span>{t("Terlambat")}</span><strong>{summary.overdue}</strong><small>{t("Belum diselesaikan")}</small></article></section>
 <section className="panel mail-table-panel"><div className="mail-toolbar"><label className="mail-search"><span><Icon name="search"/></span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={t("Cari agenda, lokasi, atau penanggung jawab...")}/></label><input className="calendar-month-filter" type="month" value={month} onChange={e=>{setMonth(e.target.value);setPage(1)}}/><label className="filter-label">{t("Status")}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="Semua">{t("Semua")}</option>{OFFICE_EVENT_STATUSES.map(x=><option key={x}>{t(x)}</option>)}</select></label></div>
 <div className="calendar-list">{loading?<p className="empty">{t("Memuat agenda...")}</p>:events.length===0?<p className="empty">{t("Belum ada agenda pada periode ini.")}</p>:events.map(e=><article key={e.id} className={e.overdue?"calendar-event overdue":"calendar-event"}><time><strong>{e.eventDate.slice(8,10)}</strong><span>{e.eventDate.slice(0,7)}</span><small>{e.startTime}{e.endTime?`–${e.endTime}`:""}</small></time><div><span className={`event-priority priority-${e.priority.toLowerCase()}`}>{t(e.priority)}</span><h3>{e.title}</h3><p>{t(e.eventType)} · {e.location}</p><small>{t("Penanggung Jawab")}: {e.responsiblePerson}</small>{e.description&&<small>{e.description}</small>}</div><span className="task-status-badge">{t(e.status)}</span><aside>{canWrite&&<button onClick={()=>openEdit(e)}><Icon name="edit"/></button>}{role==="Administrator"&&<button onClick={()=>void remove(e)}><Icon name="trash"/></button>}</aside></article>)}</div><Pagination currentPage={page} totalItems={total} perPage={perPage} onPageChange={setPage}/></section>
 {show&&<div className="modal-layer"><section className="mail-modal"><div className="modal-heading"><div><p className="eyebrow">{t("FORMULIR AGENDA")}</p><h2>{t(editing?"Edit Agenda":"Tambah Agenda")}</h2></div><button onClick={()=>setShow(false)}>×</button></div><form onSubmit={submit}><div className="form-grid"><label className="wide">{t("Judul Agenda")} *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>{t("Kategori")}<select value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value})}>{OFFICE_EVENT_TYPES.map(x=><option key={x}>{t(x)}</option>)}</select></label><label>{t("Tanggal")} *<input required type="date" value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})}/></label><label>{t("Waktu Mulai")} *<input required type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>{t("Waktu Selesai")}<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label><label>{t("Lokasi")} *<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>{t("Penanggung Jawab")} *<input required value={form.responsiblePerson} onChange={e=>setForm({...form,responsiblePerson:e.target.value})}/></label><label>{t("Prioritas")}<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{OFFICE_EVENT_PRIORITIES.map(x=><option key={x}>{t(x)}</option>)}</select></label><label>{t("Status")}<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{OFFICE_EVENT_STATUSES.map(x=><option key={x}>{t(x)}</option>)}</select></label><label className="wide">{t("Keterangan")}<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="form-actions"><button type="button" onClick={()=>setShow(false)}>{t("Batal")}</button><button className="save-button" disabled={saving}>{t(saving?"Menyimpan...":"Simpan Agenda")}</button></div></form></section></div>}<ToastContainer toasts={toasts} dismiss={dismiss}/></div>
}
