import { and, desc, eq, like, or, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { officeAssets } from "../../../db/schema";
import { ASSET_CATEGORIES, ASSET_CONDITIONS, ASSET_STATUSES, isAssetInspectionOverdue } from "../../office-assets";
import { addAudit, ADMIN_ROLES, auditDifference, READ_ROLES, requireRole, WRITE_ROLES } from "../../security";
import { readListQuery } from "../list-query";
import { cleanText, isIsoDate, parsePositiveId, serverError } from "../validation";

function parsePayload(payload:Record<string,unknown>){
 const quantity=Number(payload.quantity);const values={assetCode:cleanText(payload.assetCode,60),assetName:cleanText(payload.assetName,180),category:cleanText(payload.category,80),quantity,location:cleanText(payload.location,150),responsiblePerson:cleanText(payload.responsiblePerson,150),condition:cleanText(payload.condition,40),status:cleanText(payload.status,40),acquisitionDate:String(payload.acquisitionDate??""),nextInspectionDate:String(payload.nextInspectionDate??""),notes:cleanText(payload.notes,2000)};
 if(!values.assetCode||!values.assetName||!values.location||!values.responsiblePerson)return{error:"Kode aset, nama barang, lokasi, dan penanggung jawab wajib diisi."};
 if(!Number.isInteger(quantity)||quantity<1||quantity>100000)return{error:"Jumlah aset tidak valid."};
 if(!isIsoDate(values.acquisitionDate)||(values.nextInspectionDate&&!isIsoDate(values.nextInspectionDate)))return{error:"Tanggal perolehan atau pemeriksaan tidak valid."};
 if(!ASSET_CATEGORIES.includes(values.category as typeof ASSET_CATEGORIES[number])||!ASSET_CONDITIONS.includes(values.condition as typeof ASSET_CONDITIONS[number])||!ASSET_STATUSES.includes(values.status as typeof ASSET_STATUSES[number]))return{error:"Kategori, kondisi, atau status aset tidak valid."};
 return{values};
}
export async function GET(request:Request){try{const auth=await requireRole(request,READ_ROLES);if("response"in auth)return auth.response;const{page,perPage,offset,query,params}=readListQuery(request),condition=(params.get("condition")??"").trim(),conditions=[];if(query){const p=`%${query}%`;conditions.push(or(like(officeAssets.assetCode,p),like(officeAssets.assetName,p),like(officeAssets.category,p),like(officeAssets.location,p),like(officeAssets.responsiblePerson,p)))}if(condition&&condition!=="Semua")conditions.push(eq(officeAssets.condition,condition));const where=conditions.length?and(...conditions):undefined,today=new Date().toISOString().slice(0,10),db=await getDb();const[items,[total],[summary]]=await Promise.all([db.select().from(officeAssets).where(where).orderBy(desc(officeAssets.acquisitionDate),desc(officeAssets.id)).limit(perPage).offset(offset),db.select({value:sql<number>`count(*)`}).from(officeAssets).where(where),db.select({records:sql<number>`count(*)`,units:sql<number>`coalesce(sum(${officeAssets.quantity}),0)`,good:sql<number>`sum(case when ${officeAssets.condition}='Baik' then ${officeAssets.quantity} else 0 end)`,repair:sql<number>`sum(case when ${officeAssets.condition}='Perlu Perbaikan' then ${officeAssets.quantity} else 0 end)`,damaged:sql<number>`sum(case when ${officeAssets.condition}='Rusak' then ${officeAssets.quantity} else 0 end)`,inspection:sql<number>`sum(case when ${officeAssets.nextInspectionDate}!='' and ${officeAssets.nextInspectionDate}<${today} and ${officeAssets.status} not in ('Hilang','Dihapuskan') then 1 else 0 end)`}).from(officeAssets)]);return Response.json({assets:items.map(x=>({...x,inspectionOverdue:isAssetInspectionOverdue(x.nextInspectionDate,x.status,today)})),pagination:{page,perPage,total:Number(total?.value??0)},summary:{records:Number(summary?.records??0),units:Number(summary?.units??0),good:Number(summary?.good??0),repair:Number(summary?.repair??0),damaged:Number(summary?.damaged??0),inspection:Number(summary?.inspection??0)},currentUser:auth.user})}catch(e){return serverError(e)}}
export async function POST(request:Request){try{const auth=await requireRole(request,WRITE_ROLES);if("response"in auth)return auth.response;const parsed=parsePayload(await request.json() as Record<string,unknown>);if("error"in parsed)return Response.json({error:parsed.error},{status:400});const db=await getDb();const[dupe]=await db.select({id:officeAssets.id}).from(officeAssets).where(eq(officeAssets.assetCode,parsed.values.assetCode)).limit(1);if(dupe)return Response.json({error:"Kode aset sudah digunakan."},{status:409});const[item]=await db.insert(officeAssets).values(parsed.values).returning();await addAudit(auth.user,"Tambah aset kantor","Inventaris & Aset",`${item.assetCode} — ${item.assetName}`,{entityId:item.id});return Response.json({asset:item},{status:201})}catch(e){return serverError(e)}}
export async function PATCH(request:Request){try{const auth=await requireRole(request,WRITE_ROLES);if("response"in auth)return auth.response;const p=await request.json() as Record<string,unknown>,id=parsePositiveId(p.id);if(!id)return Response.json({error:"ID aset tidak valid."},{status:400});const parsed=parsePayload(p);if("error"in parsed)return Response.json({error:parsed.error},{status:400});const db=await getDb(),[before]=await db.select().from(officeAssets).where(eq(officeAssets.id,id)).limit(1);if(!before)return Response.json({error:"Aset tidak ditemukan."},{status:404});const[dupe]=await db.select({id:officeAssets.id}).from(officeAssets).where(and(eq(officeAssets.assetCode,parsed.values.assetCode),sql`${officeAssets.id}!=${id}`)).limit(1);if(dupe)return Response.json({error:"Kode aset sudah digunakan."},{status:409});const[item]=await db.update(officeAssets).set({...parsed.values,updatedAt:new Date().toISOString()}).where(eq(officeAssets.id,id)).returning();await addAudit(auth.user,"Perbarui aset kantor","Inventaris & Aset",`${item.assetCode} — ${item.condition}`,auditDifference(before,item,id));return Response.json({asset:item})}catch(e){return serverError(e)}}
export async function DELETE(request:Request){try{const auth=await requireRole(request,ADMIN_ROLES);if("response"in auth)return auth.response;const id=parsePositiveId((await request.json() as{id?:unknown}).id);if(!id)return Response.json({error:"ID aset tidak valid."},{status:400});const[item]=await(await getDb()).delete(officeAssets).where(eq(officeAssets.id,id)).returning();if(!item)return Response.json({error:"Aset tidak ditemukan."},{status:404});await addAudit(auth.user,"Hapus aset kantor","Inventaris & Aset",`${item.assetCode} — ${item.assetName}`,{entityId:id});return Response.json({success:true})}catch(e){return serverError(e)}}
